import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToBuffer,
} from "@react-pdf/renderer";
import {
  CATEGORY_LABELS,
  CATEGORY_ORDER,
  STATUS_LABELS,
  calculateComplianceScore,
} from "@/lib/utils";

export interface ReportTask {
  title: string;
  citation: string;
  category: string;
  status: string;
  completedAt: Date | null;
  evidenceCount: number;
}

export interface ReportData {
  orgName: string;
  generatedAt: Date;
  score: number;
  tasks: ReportTask[];
}

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: "Helvetica" },
  header: { marginBottom: 24 },
  title: { fontSize: 20, fontFamily: "Helvetica-Bold", marginBottom: 4 },
  subtitle: { fontSize: 11, color: "#555" },
  scoreBlock: {
    marginBottom: 24,
    padding: 16,
    backgroundColor: "#f1f5f9",
    borderRadius: 4,
  },
  scoreLabel: { fontSize: 11, color: "#555", marginBottom: 4 },
  scoreValue: { fontSize: 32, fontFamily: "Helvetica-Bold" },
  sectionTitle: {
    fontSize: 13,
    fontFamily: "Helvetica-Bold",
    marginTop: 16,
    marginBottom: 8,
  },
  catRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 4,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#f1f5f9",
    paddingVertical: 6,
    paddingHorizontal: 4,
    fontFamily: "Helvetica-Bold",
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 5,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  colTitle: { width: "40%", paddingRight: 6 },
  colCitation: { width: "20%" },
  colStatus: { width: "15%" },
  colDate: { width: "15%" },
  colEvidence: { width: "10%", textAlign: "right" },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 40,
    right: 40,
    fontSize: 8,
    color: "#94a3b8",
    textAlign: "center",
  },
});

function formatDate(date: Date | null): string {
  if (!date) return "—";
  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(date);
}

function ReportDocument({ data }: { data: ReportData }) {
  const categoryScores = CATEGORY_ORDER.map((category) => {
    const catTasks = data.tasks.filter((t) => t.category === category);
    return {
      category,
      score: calculateComplianceScore(catTasks),
      complete: catTasks.filter((t) => t.status === "COMPLETE").length,
      total: catTasks.filter((t) => t.status !== "NOT_APPLICABLE").length,
    };
  }).filter((c) => c.total > 0 || true);

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>HIPAA Compliance Status Report</Text>
          <Text style={styles.subtitle}>{data.orgName}</Text>
          <Text style={styles.subtitle}>
            Generated {formatDate(data.generatedAt)}
          </Text>
        </View>

        <View style={styles.scoreBlock}>
          <Text style={styles.scoreLabel}>Overall Compliance Score</Text>
          <Text style={styles.scoreValue}>{data.score}%</Text>
        </View>

        <Text style={styles.sectionTitle}>Category Breakdown</Text>
        {categoryScores.map((c) => (
          <View key={c.category} style={styles.catRow}>
            <Text>{CATEGORY_LABELS[c.category]}</Text>
            <Text>
              {c.complete}/{c.total} complete — {c.score}%
            </Text>
          </View>
        ))}

        <Text style={styles.footer}>
          Generated by HIPAA Compliance Tracker. This report reflects
          self-reported status and is not legal advice.
        </Text>
      </Page>

      <Page size="LETTER" style={styles.page}>
        <Text style={styles.sectionTitle}>Full Task List</Text>
        <View style={styles.tableHeader}>
          <Text style={styles.colTitle}>Task</Text>
          <Text style={styles.colCitation}>Citation</Text>
          <Text style={styles.colStatus}>Status</Text>
          <Text style={styles.colDate}>Completed</Text>
          <Text style={styles.colEvidence}>Files</Text>
        </View>
        {data.tasks.map((task, i) => (
          <View key={i} style={styles.tableRow} wrap={false}>
            <Text style={styles.colTitle}>{task.title}</Text>
            <Text style={styles.colCitation}>{task.citation}</Text>
            <Text style={styles.colStatus}>
              {STATUS_LABELS[task.status] ?? task.status}
            </Text>
            <Text style={styles.colDate}>{formatDate(task.completedAt)}</Text>
            <Text style={styles.colEvidence}>{task.evidenceCount}</Text>
          </View>
        ))}

        <Text style={styles.footer}>
          Generated by HIPAA Compliance Tracker. This report reflects
          self-reported status and is not legal advice.
        </Text>
      </Page>
    </Document>
  );
}

export async function renderReportPdf(data: ReportData): Promise<Buffer> {
  return renderToBuffer(<ReportDocument data={data} />);
}
